### ISSUE TITLE
Add CLUSTER SHARDS command

### ISSUE THREAD

**Issue by sazzad16** [redis/jedis#2984] opened 2022-04-24 09:30 UTC
https://redis.io/commands/cluster-shards/

**Comment by yaopen4** [comment] 2022-04-26 17:35
Hi!
I'd love to take this as my first issue

**Comment by sazzad16** [comment] 2022-04-26 18:52
@yaopen4 You're welcome to give it a shot 😃

**Comment by wormogig** [comment] 2023-10-26 14:23
Hello.
I don't really understand the status of the issue and opened PR for it.
If the issue is not relevant - write, I will close it.

**Closed** 2023-11-14 09:51 UTC
Labels: enhancement
