### ISSUE TITLE
 Could not return the broken resource to the pool due to NullPointerException

### ISSUE THREAD

**Issue by taylorcressy** [redis/jedis#2065] opened 2019-09-20 16:57 UTC
I am currently using JedisCluster in a multithreaded environment (Spark) and executing commands in a ForkJoinPool.

### Expected behavior

I would expect that the internal management of JedisCluster handles maintaining the underlying Object Pool. Without having to manage it from the application.

### Actual behavior

I am non-deterministically getting the following exception 

Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool

The full stack trace is:

`Caused by: redis.clients.jedis.exceptions.JedisException: Could not return the broken resource to the pool
        at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:94)
        at redis.clients.jedis.JedisPool.returnBrokenResource(JedisPool.java:242)
        at redis.clients.jedis.Jedis.close(Jedis.java:3468)
        at redis.clients.jedis.JedisClusterCommand.releaseConnection(JedisClusterCommand.java:144)
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:112)
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:49)
        at redis.clients.jedis.BinaryJedisCluster.lrem(BinaryJedisCluster.java:645)
        at com.<company>.mlp.blackbird.spark.structured.reader.RedisReaderStreamManager.ackMessageOnStream(RedisReaderStreamManager.scala:62)
        at com.<company>.mlp.blackbird.spark.structured.reader.RedisOffsetAckRunnable.call(RedisReaderStreamManager.scala:76)
        at com.<company>.mlp.blackbird.spark.structured.reader.RedisOffsetAckRunnable.call(RedisReaderStreamManager.scala:72)
        at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
        at org.apache.commons.pool2.impl.LinkedBlockingDeque.putLast(LinkedBlockingDeque.java:454)
        at org.apache.commons.pool2.impl.LinkedBlockingDeque.put(LinkedBlockingDeque.java:788)
        at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:939)
        at org.apache.commons.pool2.impl.GenericObjectPool.invalidateObject(GenericObjectPool.java:618)
        at redis.clients.jedis.util.Pool.returnBrokenResourceObject(Pool.java:92)`

It appears that a connection breaks and it can't return it to the pool due to a NullPointerException.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Create ForkJoinPool with 256 parallelism
2. Run random commands repeatedly
3. Exception presents itself

### Redis / Jedis Configuration
 cluster = {
            val config = new JedisPoolConfig
            new JedisCluster(new HostAndPort(hostname, port),
              60,
              60,
              50,
              null,
              null,
              config,
              if (App.isLocal) false else true)
          }

#### Jedis version:
3.1.0

#### Redis version:
Redis 5.0.4 (AWS ElastiCache)

Let me know if more information is needed.

**Comment by sazzad16** [comment] 2019-09-27 16:40
This is a [Commons Pool issue](https://issues.apache.org/jira/browse/POOL-376). It is caused due to [regression from an earlier fix](https://issues.apache.org/jira/browse/POOL-356) which is present since `2.6.1`. A newer fix is committed by yours truly and expected to be released in version.

**Comment by sazzad16** [comment] 2019-09-27 16:42
@taylorcressy If you need the solution now, you can use Commons Pool `2.6.0` or earlier versions.

**Comment by taylorcressy** [comment] 2019-10-03 17:08
@sazzad16 Thank you will give it a shot!

**Comment by sazzad16** [comment] 2020-12-15 15:35
@taylorcressy The issue is fixed in commons-pool-2.8.0. Did you try any updated and/or old version?

**Comment by sazzad16** [comment] 2021-01-18 05:54
Closed due to inactivity.

**Closed by sazzad16** 2021-01-18 05:54 UTC
