### ISSUE TITLE
Using UnifiedJedis for making connection to list of sentinel nodes

### ISSUE THREAD

**Issue by shannonantony** [redis/jedis#2838] opened 2022-01-25 07:06 UTC
Please provide me a sample to create connection to bunch of sentinel nodes using UnifiedJedis class

thanks

Jay

**Comment by sazzad16** [comment] 2022-01-25 09:53
@shannonantony At this moment, there's no such option.

Please check #2754 for more discussion on this regard.

**Comment by sazzad16** [comment] 2022-01-25 09:53
Dupe of #2754

**Closed by sazzad16** 2022-01-25 09:53 UTC
