### ISSUE TITLE
please implements clientList  "type" param!

### ISSUE THREAD

**Issue by startjava** [redis/jedis#2627] opened 2021-08-19 07:18 UTC
please implements clientList  "type" param!

**Comment by dengliming** [comment] 2021-08-19 07:22
see https://github.com/redis/jedis/blob/7ea9ad090c8626bb815f6d3e8eb80554976b5f05/src/main/java/redis/clients/jedis/Jedis.java#L3697

**Comment by startjava** [comment] 2021-08-19 09:24
@dengliming 哈哈，邓立明，哪个版本有，我现在使用version3.6.3  !

**Comment by dengliming** [comment] 2021-08-19 09:28
@startjava We haven't released it yet. The related pr https://github.com/redis/jedis/pull/2591

**Comment by sazzad16** [comment] 2021-08-19 12:12
@startjava The feature is implemented, merged and waiting to be released in version 3.7.0. In the mean it is available in snapshots. If you're eager to use the feature, you can try either 3.7.0-SNAPSHOT or 4.0.0-SNAPSHOT.

**Closed by sazzad16** 2021-08-19 12:12 UTC

**Comment by sazzad16** [comment] 2021-08-20 09:56
Deulicate of #2589

**Comment by sazzad16** [comment] 2021-08-20 09:56
Duplicate of #2589
